### ISSUE TITLE
تعديل سطالانة

### ISSUE THREAD

**Issue by Gazzerapp-Froeid** [Gazzerapp/Gazzerapp#1155]
![Image](https://github.com/user-attachments/assets/5e998bc4-e00c-414a-adbc-14f0b7cb0d73)
![Image](https://github.com/user-attachments/assets/39456d79-5d76-4690-a43d-2614a041faa7)

**Comment by Gazzerapp-Froeid** [comment]
[Satalana.xlsx](https://github.com/user-attachments/files/18141765/Satalana.xlsx)

**Comment by Gazzerapp-Froeid** [comment]
[Satalana.xlsx](https://github.com/user-attachments/files/18141857/Satalana.xlsx)

**Comment by Gazzerapp-Froeid** [comment]
[الرفع.xlsx](https://github.com/user-attachments/files/18141985/default.xlsx)

**Comment by Gazzerapp-AbdoRagab** [comment]
[سطلانة.xlsx](https://github.com/user-attachments/files/18142489/default.xlsx)
![Image](https://github.com/user-attachments/assets/06cde4df-6b23-487c-bb88-6f2ba73ecb2f)
![Image](https://github.com/user-attachments/assets/1fae3cc9-fb52-442b-a4e1-deab05415caf)
![Image](https://github.com/user-attachments/assets/2ba9eceb-25dd-4225-873e-2c25bc55f7c5)
![Image](https://github.com/user-attachments/assets/03a7c974-7eb6-4ba6-a794-c44bd16b7fb8)
![Image](https://github.com/user-attachments/assets/eeba7ab7-ee18-44f5-845b-ec6b752d9cb1)
![Image](https://github.com/user-attachments/assets/b88a7ebb-0e82-42c6-adf4-263f6696d62f)
![Image](https://github.com/user-attachments/assets/034b4810-5e57-4a28-8f32-05f0477dbc3c)
![Image](https://github.com/user-attachments/assets/6255155b-14d5-4459-bf23-50db29439a99)
![Image](https://github.com/user-attachments/assets/3cc41010-53a4-45d9-8ea6-ae08ddfdeb4a)
![Image](https://github.com/user-attachments/assets/fc477ace-6a54-4113-bcda-0a473282c12d)
![Image](https://github.com/user-attachments/assets/cad563ba-11bc-4dbe-a64a-ed1a2cfa5f29)
![Image](https://github.com/user-attachments/assets/f5d15295-d410-4183-8eb4-7c487d79035d)
![Image](https://github.com/user-attachments/assets/cb82d46b-4d70-40fb-b4fd-d771370cda77)
![Image](https://github.com/user-attachments/assets/77ab6942-599c-4267-a334-00a817b36468)
![Image](https://github.com/user-attachments/assets/886d2642-fdf1-4c15-b0b1-a94e5c0b5a4a)
![Image](https://github.com/user-attachments/assets/86bf427c-b365-48a4-b473-32170e8f07fe)
![Image](https://github.com/user-attachments/assets/48f2faa9-4f32-4768-b998-d84c720f3988)
![Image](https://github.com/user-attachments/assets/0a697262-9eaf-44eb-8c45-d60e2ee838a6)
![Image](https://github.com/user-attachments/assets/f08fc55c-93e9-4ca1-8496-2cefac41cbae)
![Image](https://github.com/user-attachments/assets/1c2f678e-f361-4739-9a61-f3bb8a0153fe)
![Image](https://github.com/user-attachments/assets/1f0d5bcf-ad10-4a51-a2e4-07ef8e11293a)
![Image](https://github.com/user-attachments/assets/0e4b16a9-a528-45f1-a63d-03115cfac364)
![Image](https://github.com/user-attachments/assets/0af9d1d8-f612-47e3-b1d3-a7d39ec9e17c)
![Image](https://github.com/user-attachments/assets/476a7e78-8912-4167-b97a-fd0f24d0a373)
![Image](https://github.com/user-attachments/assets/a283d03d-e15f-4708-858d-5e1ebb27149f)
![Image](https://github.com/user-attachments/assets/3803112b-d292-4899-bf11-323f28233faf)
![Image](https://github.com/user-attachments/assets/e3927074-a570-4243-bd44-dc996b472c11)
![Image](https://github.com/user-attachments/assets/d811606f-25d9-4727-b60e-c33e5b86cb88)
![Image](https://github.com/user-attachments/assets/f6d38f76-896c-4636-9d72-7ef58397f61c)
![Image](https://github.com/user-attachments/assets/51d04850-3820-41d0-820e-5b9f5488e88f)
![Image](https://github.com/user-attachments/assets/77122d32-07d3-4d25-8f01-c0fd8d2acb2c)
![Image](https://github.com/user-attachments/assets/09b288c5-f2d1-4f9a-8d35-49ddaf94b32f)
![Image](https://github.com/user-attachments/assets/810e18b2-78f5-4694-9eca-102f90fdfb4a)
![Image](https://github.com/user-attachments/assets/f7acd6fa-0d9a-42d7-9c99-83ae1cee6b5c)
![Image](https://github.com/user-attachments/assets/8d3e0bbd-a0bb-4d81-b679-746d85253ac8)
![Image](https://github.com/user-attachments/assets/16bdf73e-9259-443d-939a-67d406f7b3a4)
![Image](https://github.com/user-attachments/assets/23ee8938-033d-4a25-8b94-0b29458a4ddf)
![Image](https://github.com/user-attachments/assets/064a18cb-4930-4c5b-8f41-42fce507c5d3)
![Image](https://github.com/user-attachments/assets/3e576461-1bea-4dfb-ad13-e86479e34746)
![Image](https://github.com/user-attachments/assets/543f35ab-9216-4a78-9944-59c5a4850735)
![Image](https://github.com/user-attachments/assets/9954da74-7519-489c-8b9f-a9117b24951a)
![Image](https://github.com/user-attachments/assets/a006559a-d422-4056-9aaa-7394744fb0b5)
![Image](https://github.com/user-attachments/assets/e9c24e75-b51d-4244-8879-849af85a2f67)
![Image](https://github.com/user-attachments/assets/8828810d-2966-4b4f-86c3-16224505cdaa)
![Image](https://github.com/user-attachments/assets/ea61c5a5-e3b1-4d4f-a238-412035bfd04f)
![Image](https://github.com/user-attachments/assets/29caca0c-ff5f-4a30-91ac-c583d5fc3d56)
![Image](https://github.com/user-attachments/assets/245c9c83-6641-4e11-abd7-c44d5835ec38)
![Image](https://github.com/user-attachments/assets/dc80a226-76fb-47ad-9de4-0607e82b58b0)
![Image](https://github.com/user-attachments/assets/71b70ca9-7fb0-456c-ac5e-30ab31fceaa7)
![Image](https://github.com/user-attachments/assets/83f487ad-0ab1-416e-b49a-c166874d7cbf)
![Image](https://github.com/user-attachments/assets/e89f3e11-d86e-47ee-b247-25edf4818bbc)
![Image](https://github.com/user-attachments/assets/6c645b62-6bea-49d3-832b-327873ff1209)
![Image](https://github.com/user-attachments/assets/e428bdbf-eb1a-4d0f-b75d-29fe2c0c5238)
![Image](https://github.com/user-attachments/assets/8c2e9e7e-451b-46db-ab0d-c22d189117d2)
![Image](https://github.com/user-attachments/assets/b58d5e96-6a34-4423-986e-58ee25293f71)
![Image](https://github.com/user-attachments/assets/8ada871f-d3d6-4131-8e6c-42ec65e7f847)
![Image](https://github.com/user-attachments/assets/56453e13-2852-4df9-b1ec-acd2306c0602)
![Image](https://github.com/user-attachments/assets/6ef7b991-898e-430f-adf6-8cf8c1a2757b)
![Image](https://github.com/user-attachments/assets/15c29494-9a42-48a1-8daa-1e7e10aad5e2)
![Image](https://github.com/user-attachments/assets/fe8f62e4-1d2e-4e3b-bf3e-9059f8a0ea0d)
![Image](https://github.com/user-attachments/assets/7df00857-ed3c-4231-9d89-44fb87870766)

**Comment by Gazzerapp-AbdoRagab** [comment]
[سطلانة.xlsx](https://github.com/user-attachments/files/18154023/default.xlsx)

**Comment by Gazzerapp-AbdoRagab** [comment]
[سطلانة.xlsx](https://github.com/user-attachments/files/18155243/default.xlsx)

**Comment by Gazzerapp-Froeid** [comment]
On Mon, Dec 16, 2024, 08:17 pm Gazzerapp-AbdoRagab ***@***.***> wrote: 
   
  
  
   
  Closed #1155 as completed. 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Gazzerapp/Gazzerapp/issues/1155#event-15674533333",
"url": "https://github.com/Gazzerapp/Gazzerapp/issues/1155#event-15674533333",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
