### ISSUE TITLE
100076

### ISSUE THREAD

**Issue by Gazzerapp-TarekNasr** [Gazzerapp/Gazzerapp#127]

**Comment by Gazzerapp-Hossam** [comment]
مطعم فرانك مش مشغل الابلكيشن فا خلى الدليفرى يتواصل معاه و هو رقمه 
01018965293

**Comment by Gazzerapp-Hossam** [comment]
ساندوتش تشيزى بوم وصل تشيكن بدل البيف ومحتاج الدليفرى يرجع للمطعم تانى
